### ISSUE TITLE
Remove the A next to grades.

### ISSUE THREAD

**Issue by jasonhartline** [madhavsuresh/mtalib#14]
Grades that are automatically set are depicted with an A next to them.  Students think this means they get the letter grade "A".  Lets remove this to avoid confusion.

**Comment by madhavsuresh** [comment]
figure out what the "Plus" is as well. check submissionID=685

**Comment by madhavsuresh** [comment]
https://github.com/madhavsuresh/mta/commit/0bb84abc5647c55e6746f3eae9843f7798d75405
