### ISSUE TITLE
API endpoint to update peer review grades.

### ISSUE THREAD

**Issue by jasonhartline** [madhavsuresh/mtalib#9]
Madhav, you said that the API endpoint for setting peer review grades does not do update?  I need one for update soon.

**Comment by madhavsuresh** [comment]
pretty sure this is fixed, will double check

**Comment by madhavsuresh** [comment]
https://github.com/madhavsuresh/mta/commit/ee57c289c4f8423ae1cff9e4c6e5d01e981a726c
